// src/utils/validateEmail.js
// Blocks known disposable/temporary email domains

const DISPOSABLE_DOMAINS = new Set([
  // Major temp mail providers
  'mailinator.com', 'guerrillamail.com', 'guerrillamail.net', 'guerrillamail.org',
  'guerrillamail.biz', 'guerrillamail.de', 'guerrillamail.info',
  'tempmail.com', 'temp-mail.org', 'temp-mail.io', 'tempmail.net',
  'throwam.com', 'throwam.net', 'throwaway.email',
  'yopmail.com', 'yopmail.fr', 'yopmail.net',
  'sharklasers.com', 'guerillamail.info', 'grr.la', 'guerillamail.biz',
  'guerillamail.de', 'guerillamail.net', 'guerillamail.org', 'guerillamail.com',
  'spam4.me', 'trashmail.com', 'trashmail.me', 'trashmail.net',
  'trashmail.at', 'trashmail.io', 'trashmail.xyz',
  'dispostable.com', 'disposemail.com',
  'mailnull.com', 'mailnesia.com', 'mailnull.com',
  'maildrop.cc', 'mailsac.com', 'mailscrap.com',
  'fakeinbox.com', 'fakeinbox.net', 'fakemail.net',
  'spamgourmet.com', 'spamgourmet.net', 'spamgourmet.org',
  'spamhereplease.com', 'spamhereplease.net',
  'spamspot.com', 'spamthisplease.com',
  'discard.email', 'discardmail.com', 'discardmail.de',
  'crazymailing.com', 'drdrb.com', 'drdrb.net',
  'emkei.cz', 'emkei.ga', 'emkei.gq', 'emkei.ml',
  'filzmail.com', 'filzmail.de',
  'getnada.com', 'getonemail.com', 'getonemail.net',
  'giveh2o.info', 'haltospam.com', 'hatespam.org',
  'hidemail.de', 'hidzz.com', 'hmamail.com',
  'imails.info', 'inboxalias.com', 'inboxbear.com',
  'jetable.com', 'jetable.fr.nf', 'jetable.net', 'jetable.org',
  'kasmail.com', 'klassmaster.com', 'klassmaster.net',
  'klzlk.com', 'kurzepost.de', 'letthemeatspam.com',
  'lhsdv.com', 'lifebyfood.com', 'link2mail.net',
  'litedrop.com', 'lol.ovpn.to', 'lookugly.com',
  'lortemail.dk', 'lr78.com', 'lukop.dk',
  'm21.cc', 'mail-filter.com', 'mail-temporaire.com',
  'mail-temporaire.fr', 'mail.by', 'mail1a.de',
  'mailbidon.com', 'mailbiz.biz', 'mailblocks.com',
  'mailbucket.org', 'mailcat.biz', 'mailcatch.com',
  'mailchop.com', 'mailde.org', 'maileater.com',
  'mailed.in', 'mailexpire.com', 'mailf5.com',
  'mailfall.com', 'mailfree.ga', 'mailguard.de',
  'mailhazard.com', 'mailhazard.us', 'mailim.de',
  'mailin8r.com', 'mailinater.com', 'mailinator.net',
  'mailinator.org', 'mailinator2.com', 'mailincubator.com',
  'mailismagic.com', 'mailme.ir', 'mailme.lv',
  'mailme24.com', 'mailmetrash.com', 'mailmoat.com',
  'mailnew.com', 'mailnewsco.com', 'mailnobody.com',
  'mailNull.com', 'mailpick.biz', 'mailproxsy.com',
  'mailquack.com', 'mailrock.biz', 'mailsiphon.com',
  'mailslite.com', 'mailsofts.com', 'mailspam.me',
  'mailspam.net', 'mailspam.xyz', 'mailsucker.net',
  'mailtemporal.com', 'mailtemporaire.com', 'mailtemporaire.fr',
  'mailtrash.net', 'mailtv.net', 'mailtv.tv',
  'mailzilla.com', 'mailzilla.org', 'mbx.cc',
  'mega.zik.dj', 'meltmail.com', 'messagebeamer.de',
  'mezimages.net', 'mfsa.ru', 'mhzayt.online',
  'mierdamail.com', 'mintemail.com', 'mji.ro',
  'moncourrier.fr.nf', 'monemail.fr.nf', 'monmail.fr.nf',
  'msa.minsmail.com', 'mt2009.com', 'mt2014.com',
  'mt2015.com', 'mvat.de', 'mvrht.com',
  'myrealbox.com', 'myzx.com', 'n2.cl',
  'netzidiot.de', 'nevermail.de', 'newbpotato.tk',
  'noclickemail.com', 'nogmailspam.info', 'nomail.pw',
  'nomail.xl.cx', 'nomail2me.com', 'nomorespamemails.com',
  'nonspam.eu', 'nonspammer.de', 'nothingtoseehere.ca',
  'nowmymail.com', 'nurfuerspam.de', 'nus.edu.sg',
  'objectmail.com', 'obobbo.com', 'odnorazovoe.ru',
  'oneoffemail.com', 'oneoffmail.com', 'onewaymail.com',
  'online.ms', 'oopi.org', 'ordinaryamerican.net',
  'otherinbox.coM', 'otherinbox.com', 'ovpn.to',
  'owlpic.com', 'pancakemail.com', 'paplease.com',
  'pcusers.otherinbox.com', 'pepbot.com', 'pgmail.email',
  'phentermine-mortgages.com', 'pimpedupmyspace.com', 'plexolan.de',
  'poczta.onet.pl', 'politikerclub.de', 'poofy.org',
  'pookmail.com', 'privacy.net', 'privatdemail.net',
  'proxymail.eu', 'psoxs.com', 'punkass.com',
  'put2.net', 'putthisinyourspamdatabase.com', 'qq.com',
  'quickinbox.com', 'quickmail.nl', 'rcpt.at',
  'reallymymail.com', 'reconmail.com', 'reddithub.com',
  'regbypass.com', 'regbypass.coM', 'rev-zone.net',
  'rfc822.org', 'rhyta.com', 'rklips.com',
  'rmqkr.net', 'rppkn.com', 'rtrtr.com',
  's0ny.net', 'safe-mail.net', 'safetymail.info',
  'safetypost.de', 'sandelf.de', 'saynotospams.com',
  'selfdestructingmail.com', 'selfdestructingmail.org',
  'sendspamhere.com', 'shieldedmail.com', 'shiftmail.com',
  'shitmail.me', 'shortmail.net', 'sibmail.com',
  'skeefmail.com', 'slaskpost.se', 'slopsbox.com',
  'smellfear.com', 'snakemail.com', 'sneakemail.com',
  'sneakmail.de', 'snkmail.com', 'sofimail.com',
  'solvemail.info', 'soodomail.com', 'soodonims.com',
  'spam.la', 'spam.mn', 'spam.su', 'spam4.me',
  'spamavert.com', 'spambob.com', 'spambob.net',
  'spambob.org', 'spambog.com', 'spambog.de',
  'spambog.ru', 'spambox.info', 'spambox.irishspringrealty.com',
  'spambox.us', 'spamcannon.com', 'spamcannon.net',
  'spamcon.org', 'spamcorptastic.com', 'spamcowboy.com',
  'spamcowboy.net', 'spamcowboy.org', 'spamday.com',
  'spamex.com', 'spamfree.eu', 'spamfree24.de',
  'spamfree24.eu', 'spamfree24.info', 'spamfree24.net',
  'spamfree24.org', 'spamgoes.in', 'spamgourmet.com',
  'spamgourmet.net', 'spamgourmet.org', 'spamherelots.com',
  'spamhereplease.com', 'spamhole.com', 'spamify.com',
  'spaminator.de', 'spamkill.info', 'spaml.com',
  'spaml.de', 'spammotel.com', 'spammy.host',
  'spamoff.de', 'spamoverflow.net', 'spampass.com',
  'spamserver.de', 'spamserver2.de', 'spamspot.com',
  'spamstack.net', 'spamthisplease.com', 'spamtrail.com',
  'spamtrap.ro', 'spamtroll.net', 'speed.1s.fr',
  'spoofmail.de', 'squizzy.de', 'squizzy.eu',
  'squizzy.net', 'stinkefinger.net', 'suburbanthug.com',
  'supergreatmail.com', 'supermailer.jp', 'superrito.com',
  'superstachel.de', 'suremail.info', 'svk.jp',
  'sweetxxx.de', 'tafmail.com', 'tagyourself.com',
  'teewars.org', 'teleworm.com', 'teleworm.us',
  'tempalias.com', 'tempe-mail.com', 'tempemail.biz',
  'tempemail.com', 'tempemail.net', 'tempinbox.co.uk',
  'tempinbox.com', 'tempmail.eu', 'tempmail.it',
  'tempmailer.com', 'tempmailer.de', 'tempomail.fr',
  'temporaryemail.net', 'temporaryemail.us', 'temporaryforwarding.com',
  'temporaryinbox.com', 'temporarymail.org', 'tempsky.com',
  'tempthe.net', 'thanksnospam.info', 'thisisnotmyrealemail.com',
  'throam.com', 'throwam.com', 'throwaway.email',
  'throwam.net', 'tilien.com', 'tittbit.in',
  'tizi.com', 'tmailinator.com', 'toiea.com',
  'tradermail.info', 'trash-amil.com', 'trash-mail.at',
  'trash-mail.com', 'trash-mail.de', 'trash-mail.ga',
  'trash-mail.io', 'trash-mail.ml', 'trash-mail.net',
  'trash2009.com', 'trashdevil.com', 'trashdevil.de',
  'trashemail.de', 'trashemails.de', 'trashimail.com',
  'trashmail.app', 'trashmail.at', 'trashmail.com',
  'trashmail.eu', 'trashmail.fr', 'trashmail.ga',
  'trashmail.gq', 'trashmail.io', 'trashmail.me',
  'trashmail.ml', 'trashmail.net', 'trashmail.org',
  'trashmail.xyz', 'trashmailer.com', 'trashpanda.de',
  'trashware.net', 'trashymail.com', 'trbvm.com',
  'trickmail.net', 'trillianpro.com', 'tryalert.com',
  'tufmail.com', 'turual.com', 'twinmail.de',
  'tyldd.com', 'ugmail.org', 'umail.net',
  'uroid.com', 'us.af', 'venompen.com',
  'veryrealemail.com', 'viditag.com', 'viralplays.com',
  'vitedomain.com', 'vivavelocity.com', 'vmailing.info',
  'vmani.com', 'voidbay.com', 'vomoto.com',
  'vpn.st', 'vsimcard.com', 'vubby.com',
  'warnwire.com', 'webemail.me', 'webm4il.info',
  'wegwerfmail.de', 'wegwerfmail.net', 'wegwerfmail.org',
  'wetrainbayarea.org', 'whyspam.me', 'willhackforfood.biz',
  'willselfdestruct.com', 'wilemail.com', 'winemaven.info',
  'wronghead.com', 'wuzup.net', 'wuzupmail.net',
  'www.e4ward.com', 'www.gishpuppy.com', 'www.mailinator.com',
  'wwwnew.eu', 'xagloo.co', 'xagloo.com',
  'xemaps.com', 'xents.com', 'xmaily.com',
  'xoxy.net', 'xrvpm.net', 'yapped.net',
  'yeah.net', 'yellowhat.org', 'yep.it',
  'yogamaven.com', 'yomail.info', 'yopmail.com',
  'yopmail.fr', 'yopmail.net', 'youmail.ga',
  'yourdomain.com', 'yuurok.com', 'z1p.biz',
  'za.com', 'zehnminuten.de', 'zehnminutenmail.de',
  'zippymail.info', 'zoemail.com', 'zoemail.net',
  'zoemail.org', 'zomg.info', 'zxcv.com',
  'zxcvbnm.com', 'zzz.com',
  // Common Indian temp mail providers
  'mailtemp.in', 'tempmail.in', 'spamgenie.in',
]);

/**
 * Returns true if the email is from a known disposable domain.
 */
export function isDisposableEmail(email) {
  if (!email || !email.includes('@')) return false;
  const domain = email.split('@')[1].toLowerCase().trim();
  return DISPOSABLE_DOMAINS.has(domain);
}

/**
 * Returns true if the email looks like a real/genuine address.
 * Allows Gmail, Outlook, Yahoo, educational, corporate, etc.
 */
export function isGenuineEmail(email) {
  if (!email) return false;
  // Basic format check
  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/;
  if (!emailRegex.test(email)) return false;
  // Block disposable domains
  if (isDisposableEmail(email)) return false;
  return true;
}
